---

- hosts: all
  become: yes
  tasks:
    
    - name: setup repo for mysql latest
      yum:
        name: http://repo.mysql.com/mysql57-community-release-el7-10.noarch.rpm
        state: latest
      check_mode: yes
